#!/bin/sh
# with-clean-target.sh
# ---------------------
# Wrapper that fixes two issues caused by the workspace living on
# /Volumes/Extreme SSD/ (an external, non-APFS volume):
#
#   (1) macOS writes AppleDouble `._*` companion files when source files are
#       read/written. Those ghosts leak into ESLint scans, tsc's file walker,
#       and — worst — tauri-build.rs's permission resolver, which panics on
#       `._default.toml` in target/.../out/permissions/.../autogenerated/.
#
#   (2) cargo's target/ dir on the external volume attracts the same ghosts
#       every build.
#
# Fix: strip the ghosts and force cargo outputs to APFS-home where they don't
# get created.
#
# Usage in package.json scripts:  sh scripts/with-clean-target.sh <command...>

set -e

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

if [ "$(uname)" = "Darwin" ]; then
  find "$ROOT" -maxdepth 1 -name "._*" -type f -delete 2>/dev/null || true
  find "$ROOT/apps" "$ROOT/packages" "$ROOT/scripts" "$ROOT/.github" \
    -name "._*" -type f -delete 2>/dev/null || true
  rm -rf "$ROOT/apps/desktop/src-tauri/target" 2>/dev/null || true
  rm -rf "$ROOT/apps/desktop/src-tauri/gen" 2>/dev/null || true
  if [ -d "$HOME/.cargo/target/sramp-desktop" ]; then
    find "$HOME/.cargo/target/sramp-desktop" -name "._*" -type f -delete 2>/dev/null || true
  fi
fi

if [ -z "${CARGO_TARGET_DIR:-}" ]; then
  export CARGO_TARGET_DIR="$HOME/.cargo/target/sramp-desktop"
fi

# Vite is configured strictPort: true in apps/desktop/vite.config.ts — if :1420
# is held by a zombie from a prior SIGTERMed run, the dev server fails fast.
# Proactively release vite's port before launching. Only the Tauri dev port is
# controlled here; ffmpeg/HTTP/etc. listeners are not touched.
for port in 1420; do
  if lsof -ti :"$port" >/dev/null 2>&1; then
    victims=$(lsof -ti :"$port" 2>/dev/null | tr '\n' ' ')
    echo "[with-clean-target] releasing :$port (PIDs: $victims)" >&2
    # Unquoted on purpose: lsof emits one PID per line; the shell word-splits
    # on IFS into multiple kill args. Don't quote $victims below.
    kill $victims 2>/dev/null || true
    sleep 2
    if lsof -ti :"$port" >/dev/null 2>&1; then
      holdouts=$(lsof -ti :"$port" 2>/dev/null | tr '\n' ' ')
      kill -9 $holdouts 2>/dev/null || true
      sleep 1
    fi
  fi
  # Give the OS a moment to clear TIME_WAIT / close sockets fully.
  sleep 2
done

# A SIGTERMed `tauri dev` run leaves the compiled sramp-desktop binary
# running with its WKWebView attached to the dead vite. macOS's
# `com.apple.WebKit.Networking` XPC service keeps an ESTABLISHED socket on
# 1420 from that webview. Killing the binary first lets WebKit time out and
# exit on its own. Exact-name match (`pgrep -x`) — only targets processes
# literally named sramp-desktop, not anything else.
if command -v pgrep >/dev/null 2>&1; then
  desk_pids=$(pgrep -x sramp-desktop 2>/dev/null || true)
  if [ -n "$desk_pids" ]; then
    echo "[with-clean-target] killing stale sramp-desktop (PIDs: $desk_pids)" >&2
    kill -9 $desk_pids 2>/dev/null || true
    sleep 1
  fi
fi

exec "$@"
